### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/driving-game#1]
https://github.com/Learning-Fuze/driving-game-instructions

## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create html, css, & js docs
- [x] link them together and test to make sure they linked correctly
- [x] add background color
- [x] add image of car
