### ISSUE TITLE
issue-2-user-can-turn-their-car

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create down key event listener
- [x] add directional classes for the car to be turned
- [x] depending on the arrow key being hit, transform: rotate; the image of the car
