### ISSUE TITLE
issue-3-user-can-start-their-car

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add inline styling to car, position: absolute;
- [x] retrieve the car's style from the DOM
- [x] add interval function to increase value of x movement to car
- [x] add event listener on keyboard to toggle interval function on/off
