### ISSUE TITLE
issue-5-user-can-steer-their-car

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/driving-game#9]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] create x and y coordinate place holders
- [x] add functionality to either add or subtract from x or y coordinate
- [x] if up down is pushed, change top
- [x] if left right is pushed, change left
